config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "events#index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  
  resources :users
  resources :sessions
  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  has_many :event_attendings, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendings, source: :event_attendee 

  scope :upcoming, ->{ where('schedule > ?', DateTime.now ) }
  scope :past, ->{ where('schedule < ?', DateTime.now ) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendings

  

  def self.authenticate(username)
    user = find_by_username(username)
    if user
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: [:new, :create, :delete]

  def new
    @event = current_user.created_events.build
  end

  def create  
    @event = current_user.created_events.build(user_params)
    if @event.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy 

    redirect_to root_path :notice => "event deleted"
  end

  private

  def user_params
    params.require(:event).permit(:name, :location, :schedule)
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_url # halts request cycle
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
      user = User.authenticate(params[:username])
      if user
      # session[:user_id] = user.id
      log_in user
      redirect_to root_url, :notice => 'logged in!'
    else
      flash.now[:alert] = 'user not found'
      render 'new'
    end
  end


  def destroy
    log_out
    redirect_to root_url, :notice => 'logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, :notice => "#{@user.name} Successfully Created"
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy 

    redirect_to root_path
  end

  def index
    @users = User.all
    current_user = User.find_by_id(session[:current_user_id])
  end

  def show
    @user = User.find(params[:id])
  end



  private

  def user_params
    params.require(:user).permit(:name, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="my-10 mx-6 grid grid-cols-2 gap-6 auto-rows-auto grid-flow-col overflow-hidden">

  <div class="bg-gray-50 shadow-xl overflow-hidden ">
    <h1 class="text-center" >Upcoming Events</h1>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
      <% @events.upcoming.each do |e| %> 

        <div class="max-w-xs rounded overflow-hidden shadow-lg my-2">
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">Event: <%= e.id %></div>
            <p class="text-grey-darker text-base">
            <i>NAME: </i> <%= e.name %> <br>
            <i>LOCATION: </i> <%= e.location %> <br>
            <i>CREATOR: </i> <%= e.creator.name %>  <br>
            <i>SCHEDULE: </i> <%= e.schedule %>  <br>
            </p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Show", e %></span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Delete", e, method: :delete, data: { confirm: "Are you sure?" } %></span>
          </div>
        </div>

      <% end %>

    </div>
  </div>

  <div class="bg-gray-50 shadow-xl overflow-hidden">
    <h1 class="text-center" >Past Events</h1>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
      <% @events.past.each do |e| %> 

        <div class="max-w-xs rounded overflow-hidden shadow-lg my-2">
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">Event: <%= e.id %></div>
            <p class="text-grey-darker text-base">
            <i>NAME: </i> <%= e.name %> <br>
            <i>LOCATION: </i> <%= e.location %> <br>
            <i>CREATOR: </i> <%= e.creator.name %>  <br>
            <i>SCHEDULE: </i> <%= e.schedule %>  <br>
            </p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Show", e %></span>
            <% if logged_in? && e.creator.name == current_user.name  %>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Delete", e,  :method => :delete, :confirm => "Are you sure?"  %></span>
            <% end %>
          </div>
        </div>

      <% end %>

    </div>
  </div>

</div>

<!-- 
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">

<% @events.upcoming.each do |e| %> 
<h1>Upcoming Events</h1>
  <div class="max-w-xs rounded overflow-hidden shadow-lg my-2">
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2">Event: <%= e.id %></div>
      <p class="text-grey-darker text-base">
      <i>NAME: </i> <%= e.name %> <br>
      <i>LOCATION: </i> <%= e.location %> <br>
      <i>CREATOR: </i> <%= e.creator.name %>  <br>
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Show", e %></span>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to "Delete", e, method: :delete, data: { confirm: "Are you sure?" } %></span>
    </div>
  </div>

<% end %>

</div>

-->

app/views/events/new.html.erb
<div class="py-20 h-screen bg-gray-300 px-2">
    <div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-md">
        <div class="md:flex">
            <div class="w-full p-3 px-6 py-10">
              <%= form_for(@event) do |f| %>
                <div class="text-center"> <span class="text-xl text-gray-700">Create Event</span> </div>
                <div class="mt-3 relative"> <span class="absolute p-1 bottom-8 ml-2 bg-white text-gray-400 ">Name</span> <%= f.text_field :name, class: "h-12 px-2 w-full border-2 rounded focus:outline-none focus:border-red-600" %> </div>
                <div class="mt-3 relative"> <span class="absolute p-1 bottom-8 ml-2 bg-white text-gray-400 ">Location</span> <%= f.text_field :location, class:"h-12 px-2 w-full border-2 rounded focus:outline-none focus:border-red-600" %> </div>          
                <div class="mt-3 relative"> <span class="absolute p-1 bottom-8 ml-2 bg-white text-gray-400 ">Schedule</span> <%= f.date_field :schedule, class:"h-12 px-2 w-full border-2 rounded focus:outline-none focus:border-red-600" %> </div>          
                <div class="mt-4"> <%= f.submit "Create", class: "h-12 w-full bg-red-600 text-white rounded hover:bg-red-700" %> </div>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<h1> EVENT</h1>

<p>Name: <%= @event.name %> </p>
<p>Location: <%= @event.location %></p>
<p>Creator: <%= @event.creator.name %></p>
<p>Attendees: </p>

<% @event.attendees.each do |attendee| %> 

<ul>
  <li>- <%= attendee.name %>  </li>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="emerald">
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/nav" %>

  <% if notice %>
    <div class="alert alert-info">
      <div class="flex-1">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-6 h-6 mx-2 stroke-current">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>                          
        </svg> 
        <label> <%= notice %> </label>
      </div>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="navbar mb-2 shadow-lg bg-neutral text-neutral-content rounded-box">
  <div class="px-2 mx-2 navbar-start">
      <%= link_to "Private Events", root_path, class: "text-2xl font-bold" %>
  </div> 
  <div class="hidden px-2 mx-2 navbar-center lg:flex">
    <div class="flex items-stretch">
      <%= link_to "Create event", new_event_path, class: "btn btn-accent btn-sm rounded-btn ml-5" %>
      <%= link_to "Browse Events", events_path, class: "btn btn-neutral btn-sm rounded-btn" %>
      <%= link_to "Find Users", users_path, class: "btn btn-neutral btn-sm rounded-btn" %>
    </div>
  </div> 
  <div class="navbar-end">
      <% if logged_in? %>
        Logged in as: <%= current_user.name %>  
        <%= link_to "Log out", log_out_path, class: "btn btn-primary btn-sm rounded-btn ml-5 mr-5" %>
      <% else %>
       <%= link_to "Create Account", new_user_path, class: "btn btn-secondary btn-outline btn-sm rounded-btn mr-5" %>
       <%= link_to "Sign In", log_in_path, class: "btn btn-primary btn-sm rounded-btn mr-5" %>
      <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">

<% @users.each do |user| %> 

  <div class="max-w-xs rounded overflow-hidden shadow-lg my-2">
    <div class="px-6 py-4">
    <h1 class="text-xl font-semibold text-gray-900 text-center my-2">
        <%= user.name %> <br>
    </h1>
    <h2 class="text-xl font-light text-gray-700 text-center my-2">
        <%= user.username%> <br>
    </h2>
    <h3 class="text-lg font-light text-gray-800 my-2">
        Created events: 
    </h3>
    <ul class="list-disc">
      <% user.created_events.each do |event| %>
        <li><%= link_to event.name, event, class: "text-blue-400 underline hover:text-blue-700 "%> </li>
      <% end %>
    </ul>
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
    </div>
  </div>

<% end %>

</div>

app/views/users/new.html.erb
<div class="py-20 h-screen px-2">
    <div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-md">
        <div class="md:flex">
            <div class="w-full p-3 px-6 py-10">
              <%= form_for(@user) do |f| %>
                <div class="text-center"> <span class="text-xl text-gray-700">Sign Up</span> </div>
                <div class="mt-3 relative"> <span class="absolute p-1 bottom-8 ml-2 bg-white text-gray-400 ">Name</span> <%= f.text_field :name, class: "h-12 px-2 w-full border-2 rounded focus:outline-none focus:border-red-600" %> </div>
                <div class="mt-3 relative"> <span class="absolute p-1 bottom-8 ml-2 bg-white text-gray-400 ">Username</span> <%= f.text_field :username, class:"h-12 px-2 w-full border-2 rounded focus:outline-none focus:border-red-600" %> </div>          
                <div class="mt-4"> <%= f.submit "Sign Up", class: "h-12 w-full bg-red-600 text-white rounded hover:bg-red-700" %> </div>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h1>User:</h1>

name: <%= @user.name %> <br>
username: <%= @user.username %> <br>
<p>upcoming events:</p>
<div> <% @user.attended_events.upcoming.each do |a| %>
 <li>- <%= a.name %> </li>
<% end %>
</div>
<p>past events:</p>
<div> <% @user.attended_events.past.each do |a| %>
 <li>- <%= a.name %> </li>
<% end %>
</div>